logging:
  level:
    root: INFO
spring:
  application:
    name: "IBIS User Service"
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgresDB"
    username: "student"
    password: "student"
    driver-class-name: org.postgresql.Driver
server:
  port: 8081
  servlet:
    context-path: "/api"
jwt.secret.key: "secret_key"
